### ISSUE TITLE
Doesn't work in VS2013

### ISSUE THREAD

**Issue by mattjohnsonpint** [jbevain/EmojiVS#1]
I installed to both VS2013 and VS2015.

It installed fine in both, but it only renders the emoji in VS2015.

:confused:

**Comment by jbevain** [comment]
Hm. Can't repro. This is going to be fun.

Which version of VS 2013 do you have installed?

**Comment by dimapasko** [comment]
@mj1856 Do you have Resharper installed on VS2013?

**Comment by mattjohnsonpint** [comment]
Yes, I have ReSharper 9 installed on VS2013, but I tested with it disabled.  I tested on my work machine when I wrote the issue originally.

_However_ - I'm WFH today, and tested on my home machine and it works!  I had VS2013 Update 4, so I thought perhaps that was it, but then I upgraded to Update 5 and it still works.  Not sure what else it could be.  I'll test a few more things tomorrow.

**Comment by CADbloke** [comment]
If you have Resharper have you seen https://github.com/hmemcpy/ReSharper.ReMoji ?

**Comment by mattjohnsonpint** [comment]
@CADbloke  - Yes, I'm using that now.

**Comment by mattjohnsonpint** [comment]
Hmmm.. checked today on the machine where it didn't work originally and now it works.  Maybe it was just me.  Not sure.

Sorry for the false alarm, and thanks!

**Comment by CADbloke** [comment]
for anyone else with this problem - I had to restart VS after installing the Resharper extension to get it all working ok. All good after that.

**Comment by jbevain** [comment]
Thanks for the heads up @CADbloke!
