### ISSUE TITLE
Intellisense doesn't work with R# installed

### ISSUE THREAD

**Issue by mattjohnsonpint** [jbevain/EmojiVS#2]
Using VS2015 with ReSharper, I can't get a dropdown with the available emoji.

It works if I suspend or uninstall ReSharper.

**Comment by jbevain** [comment]
R# highjacks the VS intellisense, that's very much expected.

We need a EmojiVS R# plugin. That's planned though, I never wrote one.

**Comment by hmemcpy** [comment]
I'm working on that :) 
![remoji](https://cloud.githubusercontent.com/assets/601206/9023123/76cc3fc6-3897-11e5-9d3b-102887c43a4d.gif)

**Comment by hmemcpy** [comment]
And it's ready! Go get it now :D https://github.com/hmemcpy/ReSharper.ReMoji

**Comment by mattjohnsonpint** [comment]
:+1: :smile: :shipit:
