### ISSUE TITLE
Option to disable extension in .xml based documents

### ISSUE THREAD

**Issue by matthewacme** [jbevain/EmojiVS#7]
Most of the time this works great, but some of the XML docs we consume from the FAA have namespace definitions that, while hilarious to see when opened, make it hard to visual look thru them.

Some options setting that allows us to specify file extensions to disable EmojiVS on.
![sillyfaanamespace notation and emojivs](https://cloud.githubusercontent.com/assets/11168104/9416040/5322587e-4811-11e5-80e8-8b560a056ed4.png)

**Comment by jbevain** [comment]
Hi!

Yeah that will be fixed through #4.

Now I just need to take the time to investigate why it introduces a bug when adding an emoji through intellisense.

Thanks!
