### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by dcolclazier** [jbevain/EmojiVS#8]
Everything works fine, except that I get nothing listed in Intellisense after typing something along the lines of :

// :   and then pressing Ctrl+space

I've installed Remoji, to no effect. Ideas?

**Comment by dcolclazier** [comment]
Actually, if I highlight the : before pressing Ctrl+space, it does in-fact pull up the list... Is this normal?

**Comment by jbevain** [comment]
Hi @dcolclazier!

If you're using ReSharper along with Remoji, it would be a Remoji bug instead, as they have their own completion for ReSharper. /cc @hmemcpy

**Comment by dcolclazier** [comment]
Awesome - thanks for the quick response.
